package br.com.platform.movies.view;

import br.com.platform.movies.controller.MoviePersonController;
import br.com.platform.movies.dto.PersonalStatisticsDTO;
import br.com.platform.movies.session.Session;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elieudo Maia
 * @author Ivanildo Borges
 */
public class EstatisticsNerds extends javax.swing.JFrame {
    private MoviePersonController moviePersonController;
    /**
     * Creates new form EstatisticsNerds
     */
    public EstatisticsNerds() {
      this.moviePersonController = new MoviePersonController();
        initComponents();
        this.loadStatistics();
    }
    
    private void loadStatistics() {
      try {
        int userId = Session.userId;
        System.out.println("dentro de stats " + Session.userId);
        PersonalStatisticsDTO stats = this.moviePersonController.getPersonalStatistics(userId);
        this.totalMinutesWatched.setText(String.valueOf(stats.getTotalMinutesWatchedByUser()));
        this.overallAverage.setText(String.valueOf(stats.getOverallAverage()));
        
        Map totalByGenre = stats.getMapTotalByGenre();
        
        System.out.println(totalByGenre.get("Ação"));
        System.out.println(totalByGenre.get("Romance"));
        System.out.println(totalByGenre.get("Comédia"));
        System.out.println(totalByGenre.get("Terror"));
        System.out.println(totalByGenre.get("Ficção Científica"));
        System.out.println(totalByGenre.get("Aventura"));
        System.out.println(totalByGenre.get("Biográfico"));
        System.out.println(totalByGenre.get("Histórico"));
        System.out.println(totalByGenre.get("Fantasia"));
        System.out.println(totalByGenre.get("Infantil"));
        System.out.println(totalByGenre.get("Musical"));
        
        int quantityWatched = 0;
        int linha = 0;
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel) this.genreTable.getModel();
        tableModel.setNumRows(0);
        
        String[] generos = {"Ação", "Romance", "Comédia", "Terror", "Ficção Científica", "Aventura", "Biográfico", "Histórico", "Fantasia", "Infantil", "Musical"};
        
        for (String genre : generos) {
          tableModel.addRow(new Object[]{
            genre,
            totalByGenre.get(genre),
            linha++
          });
        }
        
        float userAvg = stats.getUserAverage();
        float totalAvg = stats.getOverallAverage();
        String msg = "";
        if (userAvg > totalAvg) {
          float diff = userAvg - totalAvg;
          msg = "Sua média está " + String.format("%.2f", diff) + " minuto(s) acima da média geral.";
        } else if (totalAvg > userAvg){
          float diff = totalAvg - userAvg;
          msg = "Sua média está " + String.format("%.2f", diff) + " minuto(s) abaixo da média geral.";
        } else {
          msg = "Sua média de minutos assistidos é igual a média geral.";
        }
        
        this.totalAverage.setText(msg);
        
        int quantity = 0;
        for (String g : generos) {
          Object q = totalByGenre.get(g);
          if (q != null) {
            quantity += Integer.parseInt(q.toString());
          }
        }
        
        this.quantityWatched.setText(String.valueOf(quantity));
      } catch (Exception e) {
        System.out.println("Erro ao buscar estatísticas do usuário: " + e.getMessage());
      }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    back1 = new javax.swing.JButton();
    Logo = new javax.swing.JLabel();
    back = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    tableInfo = new javax.swing.JScrollPane();
    genreTable = new javax.swing.JTable();
    overallAverage = new javax.swing.JLabel();
    totalMinutesWatched = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    totalAverage = new javax.swing.JLabel();
    quantityWatched = new javax.swing.JLabel();
    backGround = new javax.swing.JLabel();

    back1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    back1.setForeground(new java.awt.Color(137, 61, 140));
    back1.setText("VOLTAR");
    back1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        back1ActionPerformed(evt);
      }
    });

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Estatísticas para Nerds");
    setResizable(false);
    getContentPane().setLayout(null);

    Logo.setFont(new java.awt.Font("Stencil", 0, 50)); // NOI18N
    Logo.setForeground(new java.awt.Color(255, 0, 0));
    Logo.setText("PLATAFORMA DE FILMES");
    getContentPane().add(Logo);
    Logo.setBounds(170, 20, 580, 60);

    back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    back.setForeground(new java.awt.Color(137, 61, 140));
    back.setText("VOLTAR");
    back.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backActionPerformed(evt);
      }
    });
    getContentPane().add(back);
    back.setBounds(20, 30, 90, 29);

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(130, 19, 138));
    jLabel4.setText("ESTATÍSTICAS");
    getContentPane().add(jLabel4);
    jLabel4.setBounds(400, 100, 170, 30);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Filmes por gênero:");
    getContentPane().add(jLabel1);
    jLabel1.setBounds(70, 250, 240, 30);

    tableInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    genreTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    genreTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null},
        {null, null}
      },
      new String [] {
        "Gênero", "Total de filmes assitidos"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean [] {
        false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tableInfo.setViewportView(genreTable);
    if (genreTable.getColumnModel().getColumnCount() > 0) {
      genreTable.getColumnModel().getColumn(0).setMinWidth(100);
      genreTable.getColumnModel().getColumn(0).setPreferredWidth(200);
      genreTable.getColumnModel().getColumn(0).setMaxWidth(200);
      genreTable.getColumnModel().getColumn(1).setResizable(false);
      genreTable.getColumnModel().getColumn(1).setMinWidth(100);
      genreTable.getColumnModel().getColumn(1).setPreferredWidth(100);
      genreTable.getColumnModel().getColumn(1).setMaxWidth(150);
      genreTable.getColumnModel().getColumn(1).setHeaderValue("Minutos gastos");
    }

    getContentPane().add(tableInfo);
    tableInfo.setBounds(70, 290, 300, 240);

    overallAverage.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    overallAverage.setForeground(new java.awt.Color(255, 255, 255));
    overallAverage.setText("0");
    getContentPane().add(overallAverage);
    overallAverage.setBounds(590, 290, 180, 30);

    totalMinutesWatched.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    totalMinutesWatched.setForeground(new java.awt.Color(255, 255, 255));
    totalMinutesWatched.setText("0");
    getContentPane().add(totalMinutesWatched);
    totalMinutesWatched.setBounds(290, 180, 110, 30);

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Total de minutos assistidos:");
    getContentPane().add(jLabel3);
    jLabel3.setBounds(70, 180, 240, 30);

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Total de filmes assistidos:");
    getContentPane().add(jLabel5);
    jLabel5.setBounds(70, 150, 210, 30);

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("minuto(s) de cada filme.");
    getContentPane().add(jLabel6);
    jLabel6.setBounds(400, 320, 190, 30);

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Você assiste, em média,  ");
    getContentPane().add(jLabel7);
    jLabel7.setBounds(400, 290, 190, 30);

    totalAverage.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    totalAverage.setForeground(new java.awt.Color(255, 255, 255));
    totalAverage.setText("Sua média está acima/abaixo 0 minutos da média geral.");
    getContentPane().add(totalAverage);
    totalAverage.setBounds(400, 390, 490, 30);

    quantityWatched.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    quantityWatched.setForeground(new java.awt.Color(255, 255, 255));
    quantityWatched.setText("0");
    getContentPane().add(quantityWatched);
    quantityWatched.setBounds(270, 150, 120, 30);

    backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/platform/movies/midia/Retângulo 1.jpg"))); // NOI18N
    getContentPane().add(backGround);
    backGround.setBounds(0, 0, 960, 590);

    setSize(new java.awt.Dimension(958, 617));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new MyAccount().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        new MyAccount().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstatisticsNerds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstatisticsNerds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstatisticsNerds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstatisticsNerds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstatisticsNerds().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Logo;
  private javax.swing.JButton back;
  private javax.swing.JButton back1;
  private javax.swing.JLabel backGround;
  private javax.swing.JTable genreTable;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel overallAverage;
  private javax.swing.JLabel quantityWatched;
  private javax.swing.JScrollPane tableInfo;
  private javax.swing.JLabel totalAverage;
  private javax.swing.JLabel totalMinutesWatched;
  // End of variables declaration//GEN-END:variables
}
