package br.com.platform.movies.view;

/**
 * 
 * @author Elieudo Maia
 * @author Ivaildo Borges
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home1
     */
    public Home() {
        initComponents();
        setSize(940, 600);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Logo = new javax.swing.JLabel();
    Banner = new javax.swing.JLabel();
    Titulo1 = new javax.swing.JLabel();
    Titulo2 = new javax.swing.JLabel();
    Titulo3 = new javax.swing.JLabel();
    Titulo4 = new javax.swing.JLabel();
    TextLogin = new javax.swing.JLabel();
    TextLogin1 = new javax.swing.JLabel();
    TextLogin2 = new javax.swing.JLabel();
    BotaoLogin = new javax.swing.JButton();
    Background = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Página Inicial");
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setPreferredSize(new java.awt.Dimension(940, 570));
    getContentPane().setLayout(null);

    Logo.setFont(new java.awt.Font("Stencil", 0, 50)); // NOI18N
    Logo.setForeground(new java.awt.Color(255, 0, 0));
    Logo.setText("PLATAFORMA DE FILMES");
    getContentPane().add(Logo);
    Logo.setBounds(170, 20, 580, 60);

    Banner.setForeground(new java.awt.Color(255, 255, 255));
    Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/platform/movies/midia/banner.png"))); // NOI18N
    getContentPane().add(Banner);
    Banner.setBounds(350, 100, 520, 170);

    Titulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    Titulo1.setForeground(new java.awt.Color(255, 255, 255));
    Titulo1.setText("Notificação de estréias de filmes,");
    getContentPane().add(Titulo1);
    Titulo1.setBounds(70, 130, 300, 40);

    Titulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    Titulo2.setForeground(new java.awt.Color(255, 255, 255));
    Titulo2.setText("acesso ilimitado a uma enorme");
    getContentPane().add(Titulo2);
    Titulo2.setBounds(70, 160, 300, 30);

    Titulo3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    Titulo3.setForeground(new java.awt.Color(255, 255, 255));
    Titulo3.setText("banca de filmes nacionais e");
    getContentPane().add(Titulo3);
    Titulo3.setBounds(70, 190, 260, 30);

    Titulo4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    Titulo4.setForeground(new java.awt.Color(255, 255, 255));
    Titulo4.setText("internacionais, e muito mais...");
    getContentPane().add(Titulo4);
    Titulo4.setBounds(70, 220, 310, 30);

    TextLogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TextLogin.setForeground(new java.awt.Color(255, 255, 255));
    TextLogin.setText("Já é usuário? Entre com sua  ");
    getContentPane().add(TextLogin);
    TextLogin.setBounds(630, 370, 220, 22);

    TextLogin1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TextLogin1.setForeground(new java.awt.Color(255, 255, 255));
    TextLogin1.setText("conta e aproveite todos os ");
    getContentPane().add(TextLogin1);
    TextLogin1.setBounds(630, 390, 210, 22);

    TextLogin2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TextLogin2.setForeground(new java.awt.Color(255, 255, 255));
    TextLogin2.setText("benefícios.");
    getContentPane().add(TextLogin2);
    TextLogin2.setBounds(630, 410, 83, 22);

    BotaoLogin.setBackground(new java.awt.Color(255, 255, 255));
    BotaoLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    BotaoLogin.setForeground(new java.awt.Color(137, 61, 140));
    BotaoLogin.setText("Entrar");
    BotaoLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotaoLoginActionPerformed(evt);
      }
    });
    getContentPane().add(BotaoLogin);
    BotaoLogin.setBounds(630, 440, 150, 40);

    Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/platform/movies/midia/Retângulo 1.jpg"))); // NOI18N
    getContentPane().add(Background);
    Background.setBounds(0, 0, 940, 570);

    setSize(new java.awt.Dimension(957, 617));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    private void BotaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLoginActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotaoLoginActionPerformed
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Background;
  private javax.swing.JLabel Banner;
  private javax.swing.JButton BotaoLogin;
  private javax.swing.JLabel Logo;
  private javax.swing.JLabel TextLogin;
  private javax.swing.JLabel TextLogin1;
  private javax.swing.JLabel TextLogin2;
  private javax.swing.JLabel Titulo1;
  private javax.swing.JLabel Titulo2;
  private javax.swing.JLabel Titulo3;
  private javax.swing.JLabel Titulo4;
  // End of variables declaration//GEN-END:variables
}