/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.platform.movies.view;

/**
 *
 * @author elieu
 */
public class Home extends javax.swing.JFrame {

  /**
   * Creates new form HomeView
   */
  public Home() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    Logo = new javax.swing.JLabel();
    Titulo1 = new javax.swing.JLabel();
    Titulo2 = new javax.swing.JLabel();
    Titulo3 = new javax.swing.JLabel();
    Titulo4 = new javax.swing.JLabel();
    TextCadastrar1 = new javax.swing.JLabel();
    TextCadastrar2 = new javax.swing.JLabel();
    TextCadastrar3 = new javax.swing.JLabel();
    BotaoCadastrar = new javax.swing.JButton();
    TextLogin1 = new javax.swing.JLabel();
    TextLogin2 = new javax.swing.JLabel();
    TextLogin3 = new javax.swing.JLabel();
    BotaoEntrar = new javax.swing.JButton();
    Banner = new javax.swing.JLabel();
    fundo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Plataforma de filmes");
    setResizable(false);

    jPanel2.setPreferredSize(new java.awt.Dimension(940, 570));
    jPanel2.setVerifyInputWhenFocusTarget(false);
    jPanel2.setLayout(null);

    Logo.setFont(new java.awt.Font("Stencil", 0, 50)); // NOI18N
    Logo.setForeground(new java.awt.Color(255, 0, 0));
    Logo.setText("PLATAFORMA DE FILMES");
    jPanel2.add(Logo);
    Logo.setBounds(170, 20, 580, 80);

    Titulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    Titulo1.setForeground(new java.awt.Color(255, 255, 255));
    Titulo1.setText("Notificação de estréias de filmes,");
    jPanel2.add(Titulo1);
    Titulo1.setBounds(70, 130, 300, 40);

    Titulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    Titulo2.setForeground(new java.awt.Color(255, 255, 255));
    Titulo2.setText("acesso ilimitado a uma enorme");
    jPanel2.add(Titulo2);
    Titulo2.setBounds(70, 160, 300, 30);

    Titulo3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    Titulo3.setForeground(new java.awt.Color(255, 255, 255));
    Titulo3.setText("banca de filmes nacionais e");
    jPanel2.add(Titulo3);
    Titulo3.setBounds(70, 190, 260, 30);

    Titulo4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    Titulo4.setForeground(new java.awt.Color(255, 255, 255));
    Titulo4.setText("internacionais, e muito mais...");
    jPanel2.add(Titulo4);
    Titulo4.setBounds(70, 220, 310, 30);

    TextCadastrar1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TextCadastrar1.setForeground(new java.awt.Color(255, 255, 255));
    TextCadastrar1.setText("Cadastre-se aqui para ter");
    jPanel2.add(TextCadastrar1);
    TextCadastrar1.setBounds(70, 340, 200, 30);

    TextCadastrar2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TextCadastrar2.setForeground(new java.awt.Color(255, 255, 255));
    TextCadastrar2.setText("acesso ilimitado a uma");
    jPanel2.add(TextCadastrar2);
    TextCadastrar2.setBounds(70, 360, 200, 30);

    TextCadastrar3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TextCadastrar3.setForeground(new java.awt.Color(255, 255, 255));
    TextCadastrar3.setText("variedade de filmes.");
    jPanel2.add(TextCadastrar3);
    TextCadastrar3.setBounds(70, 380, 200, 30);

    BotaoCadastrar.setBackground(new java.awt.Color(255, 255, 255));
    BotaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    BotaoCadastrar.setForeground(new java.awt.Color(137, 61, 140));
    BotaoCadastrar.setText("Cadastre-se");
    BotaoCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jPanel2.add(BotaoCadastrar);
    BotaoCadastrar.setBounds(70, 420, 140, 40);

    TextLogin1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TextLogin1.setForeground(new java.awt.Color(255, 255, 255));
    TextLogin1.setText("Já é usuário? Entre com sua  ");
    jPanel2.add(TextLogin1);
    TextLogin1.setBounds(600, 350, 220, 22);

    TextLogin2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TextLogin2.setForeground(new java.awt.Color(255, 255, 255));
    TextLogin2.setText("conta e aproveite todos os ");
    jPanel2.add(TextLogin2);
    TextLogin2.setBounds(600, 370, 210, 22);

    TextLogin3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    TextLogin3.setForeground(new java.awt.Color(255, 255, 255));
    TextLogin3.setText("benefícios.");
    jPanel2.add(TextLogin3);
    TextLogin3.setBounds(600, 390, 83, 22);

    BotaoEntrar.setBackground(new java.awt.Color(255, 255, 255));
    BotaoEntrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    BotaoEntrar.setForeground(new java.awt.Color(137, 61, 140));
    BotaoEntrar.setText("Entrar");
    BotaoEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    BotaoEntrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotaoEntrarActionPerformed(evt);
      }
    });
    jPanel2.add(BotaoEntrar);
    BotaoEntrar.setBounds(600, 420, 150, 40);

    Banner.setForeground(new java.awt.Color(255, 255, 255));
    Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/platform/movies/midia/banner.png"))); // NOI18N
    jPanel2.add(Banner);
    Banner.setBounds(340, 120, 520, 170);

    fundo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/platform/movies/midia/Retângulo 1.jpg"))); // NOI18N
    fundo.setText("  acesso ilimitado a uma enorme  banca de filmes nacionais e  internacionais, e muito mais...");
    fundo.setPreferredSize(new java.awt.Dimension(940, 570));
    jPanel2.add(fundo);
    fundo.setBounds(0, 0, 900, 520);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void BotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEntrarActionPerformed
    new Login().setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_BotaoEntrarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Home().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Banner;
  private javax.swing.JButton BotaoCadastrar;
  private javax.swing.JButton BotaoEntrar;
  private javax.swing.JLabel Logo;
  private javax.swing.JLabel TextCadastrar1;
  private javax.swing.JLabel TextCadastrar2;
  private javax.swing.JLabel TextCadastrar3;
  private javax.swing.JLabel TextLogin1;
  private javax.swing.JLabel TextLogin2;
  private javax.swing.JLabel TextLogin3;
  private javax.swing.JLabel Titulo1;
  private javax.swing.JLabel Titulo2;
  private javax.swing.JLabel Titulo3;
  private javax.swing.JLabel Titulo4;
  private javax.swing.JLabel fundo;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
