/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.platform.movies.view;

import br.com.platform.movies.controller.MovieController;
import javax.swing.JOptionPane;

/**
 *
 * @author elieu
 */
public class MovieForm extends javax.swing.JFrame {
  private MovieController movieController;

  /**
   * Creates new form MovieForm
   */
  public MovieForm() {
    this.movieController = new MovieController();
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        isAvailable = new javax.swing.JCheckBox();
        name = new javax.swing.JTextField();
        genre = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        register = new javax.swing.JButton();
        duration = new javax.swing.JSpinner();
        ageRange = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Filme");
        setResizable(false);

        jPanel1.setLayout(null);

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(137, 61, 140));
        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel);
        cancel.setBounds(340, 370, 105, 37);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 120, 60, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gênero:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(590, 110, 70, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 190, 90, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Duração:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(740, 190, 70, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Faixa Etária:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 190, 92, 22);

        isAvailable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        isAvailable.setForeground(new java.awt.Color(137, 61, 140));
        isAvailable.setText("Disponível");
        jPanel1.add(isAvailable);
        isAvailable.setBounds(590, 300, 110, 25);

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(name);
        name.setBounds(60, 150, 500, 26);

        genre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação", "Romance", "Comédia", "Terror", "Ficção Científica", "Drama", "Aventura", "Biográfico", "Histórico", "Fantasia", "Musical" }));
        genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreActionPerformed(evt);
            }
        });
        jPanel1.add(genre);
        genre.setBounds(590, 140, 130, 30);

        description.setColumns(20);
        description.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 220, 500, 110);

        register.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(137, 61, 140));
        register.setText("Cadastrar");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register);
        register.setBounds(480, 370, 113, 37);

        duration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(duration);
        duration.setBounds(740, 220, 100, 30);

        ageRange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(ageRange);
        ageRange.setBounds(590, 220, 100, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(130, 19, 138));
        jLabel7.setText("CADASTRO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 40, 200, 32);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/platform/movies/midia/Retângulo 1.jpg"))); // NOI18N
        jPanel1.add(BackGround);
        BackGround.setBounds(0, 0, 930, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
    new UserArea().setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_cancelActionPerformed

  private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
    String name = this.name.getText();
    String genre = (String) this.genre.getSelectedItem();
    int ageRange = (int) this.ageRange.getValue();
    int duration = (int) this.duration.getValue();
    String description= this.description.getText();
    boolean isAvailable = this.isAvailable.isSelected();
    
    try {
      this.movieController.createMovie(name, genre, description, duration, isAvailable, ageRange);
      
      JOptionPane.showMessageDialog(null, "Filme cadastrado com sucesso");
      
      new UserArea().setVisible(true);
      this.setVisible(false);
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, e.getMessage());
    }
  }//GEN-LAST:event_registerActionPerformed

    private void genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MovieForm().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JSpinner ageRange;
    private javax.swing.JButton cancel;
    private javax.swing.JTextArea description;
    private javax.swing.JSpinner duration;
    private javax.swing.JComboBox<String> genre;
    private javax.swing.JCheckBox isAvailable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
