package br.com.platform.movies.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Elieudo Maia
 * @author Ivanildo Borges
 */
public class RequestChange extends javax.swing.JFrame {

    /**
     * Creates new form RequestChange
     */
    public RequestChange() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        subTitulo = new javax.swing.JLabel();
        textName = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        textAddress = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        textPassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        textConfirmPassword = new javax.swing.JLabel();
        passwordConfimation = new javax.swing.JPasswordField();
        textEmail = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        textTel = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        textBirth = new javax.swing.JLabel();
        birthDate = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solicitação de alteração de dados");
        setResizable(false);
        getContentPane().setLayout(null);

        Logo.setFont(new java.awt.Font("Stencil", 0, 50)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 0, 0));
        Logo.setText("PLATAFORMA DE FILMES");
        getContentPane().add(Logo);
        Logo.setBounds(170, 20, 580, 60);

        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(137, 61, 140));
        back.setText("VOLTAR");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(20, 30, 90, 29);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(130, 19, 138));
        titulo.setText("Meus Dados");
        getContentPane().add(titulo);
        titulo.setBounds(400, 130, 150, 30);

        subTitulo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        subTitulo.setForeground(new java.awt.Color(255, 255, 255));
        subTitulo.setText("*Preencha somente os campos que deseja alterar!!!");
        getContentPane().add(subTitulo);
        subTitulo.setBounds(120, 180, 330, 20);

        textName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textName.setForeground(new java.awt.Color(255, 255, 255));
        textName.setText("Nome:");
        getContentPane().add(textName);
        textName.setBounds(120, 230, 60, 22);
        getContentPane().add(name);
        name.setBounds(120, 250, 340, 22);

        textAddress.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textAddress.setForeground(new java.awt.Color(255, 255, 255));
        textAddress.setText("Endereço:");
        getContentPane().add(textAddress);
        textAddress.setBounds(120, 280, 75, 22);
        getContentPane().add(address);
        address.setBounds(120, 300, 330, 22);

        textPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textPassword.setForeground(new java.awt.Color(255, 255, 255));
        textPassword.setText("Senha:");
        getContentPane().add(textPassword);
        textPassword.setBounds(120, 330, 51, 22);
        getContentPane().add(password);
        password.setBounds(120, 350, 250, 22);

        textConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        textConfirmPassword.setText("Confirmar Senha:");
        getContentPane().add(textConfirmPassword);
        textConfirmPassword.setBounds(120, 380, 132, 22);
        getContentPane().add(passwordConfimation);
        passwordConfimation.setBounds(120, 400, 250, 22);

        textEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textEmail.setForeground(new java.awt.Color(255, 255, 255));
        textEmail.setText("Email:");
        getContentPane().add(textEmail);
        textEmail.setBounds(560, 230, 47, 22);
        getContentPane().add(email);
        email.setBounds(560, 250, 310, 22);

        textTel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textTel.setForeground(new java.awt.Color(255, 255, 255));
        textTel.setText("Telefone:");
        getContentPane().add(textTel);
        textTel.setBounds(560, 280, 71, 22);

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone);
        phone.setBounds(560, 300, 190, 22);

        textBirth.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textBirth.setForeground(new java.awt.Color(255, 255, 255));
        textBirth.setText("Data de Nascimento:");
        getContentPane().add(textBirth);
        textBirth.setBounds(560, 330, 159, 22);
        getContentPane().add(birthDate);
        birthDate.setBounds(560, 350, 180, 22);

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(137, 61, 140));
        btnConfirm.setText("Confirmar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm);
        btnConfirm.setBounds(400, 460, 117, 33);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/platform/movies/midia/Retângulo 1.jpg"))); // NOI18N
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 960, 590);

        setSize(new java.awt.Dimension(958, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Perfil().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        String name = this.name.getText();
        String email = this.email.getText();
        String phone = this.phone.getText();
        String address = this.address.getText();
        String birthDate = this.birthDate.getText();
        char[] password = this.password.getPassword();
        char[] passwordConfimation = this.passwordConfimation.getPassword();

//        try {
//            
//            
//            JOptionPane.showMessageDialog(null, "Alteração encaminhada!");
//            new Perfil().setVisible(true);
//            this.setVisible(false);
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, ex.getMessage());
//        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JLabel backGround;
    private javax.swing.JTextField birthDate;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JTextField email;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField passwordConfimation;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel subTitulo;
    private javax.swing.JLabel textAddress;
    private javax.swing.JLabel textBirth;
    private javax.swing.JLabel textConfirmPassword;
    private javax.swing.JLabel textEmail;
    private javax.swing.JLabel textName;
    private javax.swing.JLabel textPassword;
    private javax.swing.JLabel textTel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
