/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.platform.movies.view;

import br.com.platform.movies.controller.PersonController;

/**
 *
 * @author elieu
 */
public class UserArea extends javax.swing.JFrame {
  private PersonController personController = new PersonController();
  private boolean isAdmin = false;
  public int personId;
  
  public void setPersonId(int id) {
    this.personId = id;
  }

  /**
   * Creates new form UserArea
   */
  public UserArea() {
    initComponents();

    System.out.println("personId" + this.personId);
    this.currentlyLoggedInUserIsAdmin();
    this.buttonCadUser.setVisible(true); // MOCK
  }
  
  private void currentlyLoggedInUserIsAdmin() {
    try {
      isAdmin = this.personController.checkIsAdmin(this.personId);
    } catch (Exception ex) {
      System.out.println("Erro ao checar se o usuário é adinistrador");
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        ButtonExit = new javax.swing.JButton();
        buttonCadFilm = new javax.swing.JButton();
        buttonCadUser = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área do Usuário");
        setResizable(false);
        setSize(new java.awt.Dimension(790, 510));
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("MINHA CONTA");
        getContentPane().add(Title);
        Title.setBounds(250, 30, 270, 60);

        ButtonExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonExit.setForeground(new java.awt.Color(137, 61, 140));
        ButtonExit.setText("Sair");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonExit);
        ButtonExit.setBounds(350, 340, 70, 33);

        buttonCadFilm.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonCadFilm.setForeground(new java.awt.Color(137, 61, 140));
        buttonCadFilm.setText("Cadastrar filme");
        buttonCadFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadFilmActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCadFilm);
        buttonCadFilm.setBounds(300, 270, 170, 31);

        buttonCadUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buttonCadUser.setForeground(new java.awt.Color(137, 61, 140));
        buttonCadUser.setText("Cadastrar usuário");
        buttonCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadUserActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCadUser);
        buttonCadUser.setBounds(300, 210, 180, 31);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/platform/movies/midia/Retângulo 1.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 790, 510);

        setSize(new java.awt.Dimension(810, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
    new Home().setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_ButtonExitActionPerformed

  private void buttonCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadUserActionPerformed
    new UserForm().setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_buttonCadUserActionPerformed

  private void buttonCadFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadFilmActionPerformed
    new MovieForm().setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_buttonCadFilmActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(UserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(UserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(UserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(UserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    
    System.out.println("args" +  args);

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new UserArea().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JLabel Title;
    private javax.swing.JButton buttonCadFilm;
    private javax.swing.JButton buttonCadUser;
    // End of variables declaration//GEN-END:variables
}
