package br.com.platform.movies.view;

import br.com.platform.movies.controller.PersonController;
import br.com.platform.movies.model.Administrator;
import br.com.platform.movies.model.Person;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elieudo Maia
 * @author Ivanildo Borges
 */
public class UserList extends javax.swing.JFrame {
    private PersonController personContoller;
    private int id;
    private boolean checkAdm;

  /**
   * Creates new form UserList
   */
  public UserList() {
      this.personContoller = new PersonController();
      initComponents();
      showInfo();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Logo = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabela = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    campo1 = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    campo3 = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    campo2 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    campo4 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    campo5 = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    campo6 = new javax.swing.JFormattedTextField();
    jLabel0 = new javax.swing.JLabel();
    register = new javax.swing.JButton();
    backGround = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Lista de Usuários");
    setResizable(false);
    getContentPane().setLayout(null);

    Logo.setFont(new java.awt.Font("Stencil", 0, 50)); // NOI18N
    Logo.setForeground(new java.awt.Color(255, 0, 0));
    Logo.setText("PLATAFORMA DE FILMES");
    getContentPane().add(Logo);
    Logo.setBounds(170, 20, 580, 60);

    jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButton3.setForeground(new java.awt.Color(137, 61, 140));
    jButton3.setText("VOLTAR");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton3);
    jButton3.setBounds(20, 30, 90, 30);

    jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButton4.setForeground(new java.awt.Color(137, 61, 140));
    jButton4.setText("CRIAR USUÁRIO");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton4);
    jButton4.setBounds(770, 30, 150, 30);

    jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Clique na linha do usuário que deseja alterar");
    getContentPane().add(jLabel8);
    jLabel8.setBounds(60, 100, 340, 30);

    tabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    tabela.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null}
      },
      new String [] {
        "Id", "Nome", "Email", "Senha", "Telefone", "Endereço", "Data de Aniversário", "Administrador"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tabela.setPreferredSize(new java.awt.Dimension(1060, 200));
    tabela.setRowHeight(20);
    tabela.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tabelaMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tabela);
    if (tabela.getColumnModel().getColumnCount() > 0) {
      tabela.getColumnModel().getColumn(0).setResizable(false);
      tabela.getColumnModel().getColumn(0).setPreferredWidth(80);
      tabela.getColumnModel().getColumn(1).setPreferredWidth(250);
      tabela.getColumnModel().getColumn(2).setPreferredWidth(250);
      tabela.getColumnModel().getColumn(3).setResizable(false);
      tabela.getColumnModel().getColumn(3).setPreferredWidth(150);
      tabela.getColumnModel().getColumn(4).setPreferredWidth(150);
      tabela.getColumnModel().getColumn(5).setPreferredWidth(200);
      tabela.getColumnModel().getColumn(6).setPreferredWidth(200);
    }

    getContentPane().add(jScrollPane1);
    jScrollPane1.setBounds(60, 130, 820, 160);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Nome");
    getContentPane().add(jLabel1);
    jLabel1.setBounds(60, 320, 60, 20);

    campo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    getContentPane().add(campo1);
    campo1.setBounds(60, 340, 440, 30);

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("Email");
    getContentPane().add(jLabel3);
    jLabel3.setBounds(590, 330, 90, 20);

    campo3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    getContentPane().add(campo3);
    campo3.setBounds(590, 410, 290, 30);

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Senha");
    getContentPane().add(jLabel5);
    jLabel5.setBounds(590, 380, 60, 30);

    campo2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    getContentPane().add(campo2);
    campo2.setBounds(590, 350, 290, 30);

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("telefone");
    getContentPane().add(jLabel2);
    jLabel2.setBounds(60, 430, 100, 30);

    campo4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    getContentPane().add(campo4);
    campo4.setBounds(60, 460, 210, 30);

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Endereço");
    getContentPane().add(jLabel6);
    jLabel6.setBounds(60, 370, 140, 30);

    campo5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    getContentPane().add(campo5);
    campo5.setBounds(60, 400, 440, 30);

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Aniversário");
    getContentPane().add(jLabel7);
    jLabel7.setBounds(590, 440, 90, 30);

    try {
      campo6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    campo6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        campo6ActionPerformed(evt);
      }
    });
    getContentPane().add(campo6);
    campo6.setBounds(590, 470, 160, 30);

    jLabel0.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    jLabel0.setForeground(new java.awt.Color(255, 255, 255));
    jLabel0.setText("Altere somente os campos que deseja atualizar");
    getContentPane().add(jLabel0);
    jLabel0.setBounds(290, 300, 380, 22);

    register.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    register.setForeground(new java.awt.Color(137, 61, 140));
    register.setText("ATUALIZAR");
    register.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        registerActionPerformed(evt);
      }
    });
    getContentPane().add(register);
    register.setBounds(420, 510, 120, 40);

    backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/platform/movies/midia/Retângulo 1.jpg"))); // NOI18N
    getContentPane().add(backGround);
    backGround.setBounds(0, 0, 960, 590);

    setSize(new java.awt.Dimension(956, 609));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    public void showInfo() {
        int linha = 0;
        List<Person> personList = this.personContoller.listAll();
        DefaultTableModel modelo;

        try {
            modelo = (DefaultTableModel) tabela.getModel();
            modelo.setNumRows(0);
            
            while (linha < personList.size()){
              
              boolean isAdmin = personList.get(linha) instanceof Administrator;
          
                modelo.addRow(new Object[]{
                    personList.get(linha).getId(),
                    personList.get(linha).getName(),
                    personList.get(linha).getEmail(),
                    personList.get(linha).getPassword(),
                    personList.get(linha).getTelephone(),
                    personList.get(linha).getAddress(),
                    personList.get(linha).getBirthDate(),
                    isAdmin ? "Sim" : "Não",//validacao para saber se é adm ou não
                    linha++
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public String convertToString(Date aniversario) {
        Date niver = aniversario;
        String dataFormatada = null;
        
        try {
            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
            dataFormatada = formatador.format(niver);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return dataFormatada;
    }
    
    public Date convertToDate(String aniversario){    
      try {      
        String day = aniversario.split("/")[0];
        String month = aniversario.split("/")[1];
        String year = aniversario.split("/")[2];
        
        Calendar cal = Calendar.getInstance();
        int dayNumber = day.startsWith("0") ? Integer.parseInt(String.valueOf(day.charAt(1))) : Integer.parseInt(day);
        int monthNumber = month.startsWith("0") ? Integer.parseInt(String.valueOf(month.charAt(1))) : Integer.parseInt(month);
        cal.set(Integer.parseInt(year), monthNumber - 1, dayNumber);
    
        Date dataFormatada = new Date(cal.getTimeInMillis());
      
        return dataFormatada;
      } catch (Exception e) {
          e.printStackTrace();
      }
      return null;
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new MyAccount().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new UserForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int linha = tabela.getSelectedRow();
        int coluna = 1;
        int colunaAux = 0;
        int identificador;
        
        try {
            System.out.println("LINHA: " + linha);
            System.out.println("COLUNA: " + coluna);

            identificador = (int) tabela.getValueAt(linha, colunaAux);
            System.out.println("ID do usuário: " + identificador);

            String nome = (String) tabela.getValueAt(linha, 1);
            String email = (String) tabela.getValueAt(linha, 2);
            String senha = (String) tabela.getValueAt(linha, 3);
            String telefone = (String) tabela.getValueAt(linha, 4);
            String endereco = (String) tabela.getValueAt(linha, 5);
            Date birthday = (Date) tabela.getValueAt(linha, 6);
            
            String resultado = convertToString(birthday);
            
            campo1.setText(nome);
            campo2.setText(email);
            campo3.setText(senha);
            campo4.setText(telefone);
            campo5.setText(endereco);
            campo6.setText(resultado);
            
            this.id = identificador;
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tabelaMouseClicked
    
    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        try {
            String nome = campo1.getText();
            String email = campo2.getText();
            String senha = campo3.getText();
            String telefone = campo4.getText();
            String endereco = campo5.getText();
            String aniversario = campo6.getText();
            
            Date resultado = convertToDate(aniversario);
            System.out.println("String Data convertida: "+resultado);
            
            System.out.println("Valor id: " + id);
            System.out.println("Valor nome: " + nome);
            System.out.println("Valor email: " + email);
            System.out.println("Valor senha: " + senha);
            System.out.println("Valor telefone: " + telefone);
            System.out.println("Valor endereco: " + endereco);
            System.out.println("Valor aniversario: " + resultado);
            
            this.personContoller.update(id, nome, email, senha, telefone, endereco, this.checkAdm, resultado);
            JOptionPane.showMessageDialog(null, "Usário atualizado com sucesso!");
            showInfo();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_registerActionPerformed

    private void campo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo6ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new UserList().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Logo;
  private javax.swing.JLabel backGround;
  private javax.swing.JTextField campo1;
  private javax.swing.JTextField campo2;
  private javax.swing.JTextField campo3;
  private javax.swing.JTextField campo4;
  private javax.swing.JTextField campo5;
  private javax.swing.JFormattedTextField campo6;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel0;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton register;
  private javax.swing.JTable tabela;
  // End of variables declaration//GEN-END:variables
}
