/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.platform.movies.view;

import br.com.platform.movies.controller.PersonController;
/**
 *
 * @author elieu
 */
public class UserArea extends javax.swing.JFrame {
  private PersonController personController = new PersonController();
  private boolean isAdmin = false;
  public int personId;
  
  public void setPersonId(int id) {
    this.personId = id;
  }

  /**
   * Creates new form UserArea
   */
  public UserArea() {
    initComponents();

    System.out.println("personId " + this.personId);
    this.currentlyLoggedInUserIsAdmin();
    this.buttonCadUser.setVisible(true); // MOCK
  }
  
  private void currentlyLoggedInUserIsAdmin() {
    try {
      isAdmin = this.personController.checkIsAdmin(this.personId);
    } catch (Exception ex) {
      System.out.println("Erro ao checar se o usuário é adinistrador");
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ButtonExit = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    buttonCadFilm = new javax.swing.JButton();
    buttonCadUser = new javax.swing.JButton();
    ButtonExit1 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    Background = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Área do Usuário");
    setResizable(false);
    setSize(new java.awt.Dimension(790, 510));
    getContentPane().setLayout(null);

    ButtonExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    ButtonExit.setForeground(new java.awt.Color(137, 61, 140));
    ButtonExit.setText("Filmes");
    ButtonExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ButtonExitActionPerformed(evt);
      }
    });
    getContentPane().add(ButtonExit);
    ButtonExit.setBounds(10, 460, 140, 33);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Meus Filmes");
    getContentPane().add(jLabel1);
    jLabel1.setBounds(10, 130, 130, 17);

    buttonCadFilm.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    buttonCadFilm.setForeground(new java.awt.Color(137, 61, 140));
    buttonCadFilm.setText("Cadastrar filme");
    buttonCadFilm.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonCadFilmActionPerformed(evt);
      }
    });
    getContentPane().add(buttonCadFilm);
    buttonCadFilm.setBounds(340, 460, 170, 31);

    buttonCadUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    buttonCadUser.setForeground(new java.awt.Color(137, 61, 140));
    buttonCadUser.setText("Cadastrar usuário");
    buttonCadUser.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonCadUserActionPerformed(evt);
      }
    });
    getContentPane().add(buttonCadUser);
    buttonCadUser.setBounds(520, 460, 180, 31);

    ButtonExit1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    ButtonExit1.setForeground(new java.awt.Color(137, 61, 140));
    ButtonExit1.setText("Sair");
    ButtonExit1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ButtonExit1ActionPerformed(evt);
      }
    });
    getContentPane().add(ButtonExit1);
    ButtonExit1.setBounds(710, 460, 70, 33);

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Nome", "Gênero", "Duração", "Tempo assistido"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(jTable1);

    getContentPane().add(jScrollPane1);
    jScrollPane1.setBounds(10, 160, 770, 220);

    Background.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    Background.setForeground(new java.awt.Color(255, 255, 255));
    Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/platform/movies/midia/Retângulo 1.jpg"))); // NOI18N
    getContentPane().add(Background);
    Background.setBounds(0, 0, 790, 510);

    setSize(new java.awt.Dimension(810, 556));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
    new Home().setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_ButtonExitActionPerformed

  private void buttonCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadUserActionPerformed
    new UserForm().setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_buttonCadUserActionPerformed

  private void buttonCadFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadFilmActionPerformed
    new MovieForm().setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_buttonCadFilmActionPerformed

  private void ButtonExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExit1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_ButtonExit1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(UserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(UserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(UserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(UserArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    
    System.out.println("args" +  args);

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new UserArea().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Background;
  private javax.swing.JButton ButtonExit;
  private javax.swing.JButton ButtonExit1;
  private javax.swing.JButton buttonCadFilm;
  private javax.swing.JButton buttonCadUser;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
